Get http://localhost:5065

###
GET http://localhost:5065/Games

###
GET http://localhost:5065/Games/1


###
POST http://localhost:5065/games
Content-Type: application/json

{
    "name": "Street Fighter II",
    "GenerID": 2,
    "price": 49.99,
    "releasDate": "2010-02-12"
}

###
PUT http://localhost:5065/games/1
Content-Type: application/json

{
    "name": "Street Fighter II Updated by ghayath 44",
    "GenerID": 3,
    "price": 39.99,
    "releasDate": "2000-02-11"
}

###
DELETE http://localhost:5065/games/2

